services:
  web:
    image: "ghcr.io/cjmalloy/jasper:${JASPER_SERVER_VERSION:-latest}"
    pull_policy: "${JASPER_SERVER_PULL:-missing}"
    ports:
      - "${JASPER_SERVER_PORT:-8081}:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "${JASPER_SERVER_PROFILES:-prod,admin,storage,feed-burst,repl-burst}"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: "${JASPER_DATABASE_PASSWORD:-jasper}"
    volumes:
      - "${JASPER_STORAGE_DIR:-/var/lib/jasper}:/var/lib/jasper"
    depends_on:
      - db
  db:
    image: "postgres:${JASPER_DATABASE_VERSION:-14.5}"
    pull_policy: "${JASPER_DATABASE_PULL:-missing}"
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: "${JASPER_DATABASE_PASSWORD:-jasper}"
      POSTGRES_DB: jasper
    volumes:
      - "${JASPER_DATA_DIR:?Must Set Data Dir}:/var/lib/postgresql/data"
  client:
    image: "ghcr.io/cjmalloy/jasper-ui:${JASPER_CLIENT_VERSION:-latest}"
    pull_policy: "${JASPER_CLIENT_PULL:-missing}"
    ports:
      - "${JASPER_CLIENT_PORT:-8082}:80"
    environment:
      JASPER_API: "http://localhost:${JASPER_SERVER_PORT:-8081}"
      JASPER_TITLE: "${JASPER_CLIENT_TITLE}"
      CSP_DEFAULT_SRC: "http://localhost:${JASPER_SERVER_PORT:-8081}"

