name: Build

on: push

permissions:
  contents: read

jobs:
  release:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: macos-latest
            target: macos-arm64
          - runner: ubuntu-latest
            target: linux-x64
          - runner: windows-latest
            target: win-x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci

      - run: npm run ci
