name: Build

on: push

permissions:
  contents: read

jobs:
  release:
    name: Build (${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: macos-26-intel
            platform: mac
            arch: x64
          - runner: macos-latest
            platform: mac
            arch: arm64
          - runner: ubuntu-latest
            platform: linux
            arch: x64
          - runner: windows-latest
            platform: win
            arch: x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci

      - run: npm run ci -- --${{ matrix.platform }} --${{ matrix.arch }}
