name: Build

on: push

permissions:
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      - run: npm run ci
